# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/xiaozhenlong/Code/TheOneEye/src/python/Views/ContentsNavWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContentsNavWin(object):
    def setupUi(self, ContentsNavWin):
        ContentsNavWin.setObjectName("ContentsNavWin")
        ContentsNavWin.resize(890, 613)
        self.gridLayout = QtWidgets.QGridLayout(ContentsNavWin)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnToTestForm = QtWidgets.QPushButton(ContentsNavWin)
        self.btnToTestForm.setMinimumSize(QtCore.QSize(0, 50))
        self.btnToTestForm.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnToTestForm.setStyleSheet("color: rgb(100, 178, 255);\n"
"background-color: rgba(82, 84, 84, 179);\n"
"border:2px solid rgb(0, 178, 255);")
        self.btnToTestForm.setObjectName("btnToTestForm")
        self.verticalLayout.addWidget(self.btnToTestForm)
        self.btnToMVForm = QtWidgets.QPushButton(ContentsNavWin)
        self.btnToMVForm.setMinimumSize(QtCore.QSize(0, 50))
        self.btnToMVForm.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnToMVForm.setStyleSheet("color: rgb(100, 178, 255);\n"
"background-color: rgba(82, 84, 84, 179);\n"
"border:2px solid rgb(0, 178, 255);")
        self.btnToMVForm.setObjectName("btnToMVForm")
        self.verticalLayout.addWidget(self.btnToMVForm)
        self.btnToNewControlForm = QtWidgets.QPushButton(ContentsNavWin)
        self.btnToNewControlForm.setMinimumSize(QtCore.QSize(0, 50))
        self.btnToNewControlForm.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnToNewControlForm.setStyleSheet("color: rgb(100, 178, 255);\n"
"background-color: rgba(82, 84, 84, 179);\n"
"border:2px solid rgb(0, 178, 255);")
        self.btnToNewControlForm.setObjectName("btnToNewControlForm")
        self.verticalLayout.addWidget(self.btnToNewControlForm)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(ContentsNavWin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 2, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbT = QtWidgets.QLabel(ContentsNavWin)
        self.lbT.setMinimumSize(QtCore.QSize(80, 100))
        self.lbT.setMaximumSize(QtCore.QSize(80, 100))
        self.lbT.setText("")
        self.lbT.setObjectName("lbT")
        self.horizontalLayout.addWidget(self.lbT)
        self.lbO = QtWidgets.QLabel(ContentsNavWin)
        self.lbO.setMinimumSize(QtCore.QSize(80, 100))
        self.lbO.setMaximumSize(QtCore.QSize(80, 100))
        self.lbO.setText("")
        self.lbO.setObjectName("lbO")
        self.horizontalLayout.addWidget(self.lbO)
        self.lbE = QtWidgets.QLabel(ContentsNavWin)
        self.lbE.setMinimumSize(QtCore.QSize(80, 100))
        self.lbE.setMaximumSize(QtCore.QSize(80, 100))
        self.lbE.setText("")
        self.lbE.setObjectName("lbE")
        self.horizontalLayout.addWidget(self.lbE)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(ContentsNavWin)
        QtCore.QMetaObject.connectSlotsByName(ContentsNavWin)

    def retranslateUi(self, ContentsNavWin):
        _translate = QtCore.QCoreApplication.translate
        ContentsNavWin.setWindowTitle(_translate("ContentsNavWin", "Form"))
        self.btnToTestForm.setText(_translate("ContentsNavWin", "To Test Form"))
        self.btnToMVForm.setText(_translate("ContentsNavWin", "To Machine Vision Form"))
        self.btnToNewControlForm.setText(_translate("ContentsNavWin", "To New Control Form"))
