# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/disk3/Code/research/TheOneEye/src/python/Views/HomePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(748, 504)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayoutViews = QtWidgets.QGridLayout()
        self.gridLayoutViews.setSpacing(0)
        self.gridLayoutViews.setObjectName("gridLayoutViews")
        self.frameViewArea = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameViewArea.sizePolicy().hasHeightForWidth())
        self.frameViewArea.setSizePolicy(sizePolicy)
        self.frameViewArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameViewArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameViewArea.setObjectName("frameViewArea")
        self.gridLayoutViews.addWidget(self.frameViewArea, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayoutViews, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
