# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/xiaozhenlong/Code/TheOneEye/src/python/Views/MachineVisionWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MachineVisionWin(object):
    def setupUi(self, MachineVisionWin):
        MachineVisionWin.setObjectName("MachineVisionWin")
        MachineVisionWin.resize(790, 555)
        self.gridLayout = QtWidgets.QGridLayout(MachineVisionWin)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(MachineVisionWin)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(7)
        self.splitter.setObjectName("splitter")
        self.gridLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutViews = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutViews.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutViews.setObjectName("gridLayoutViews")
        self.frameViewArea = QtWidgets.QFrame(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameViewArea.sizePolicy().hasHeightForWidth())
        self.frameViewArea.setSizePolicy(sizePolicy)
        self.frameViewArea.setMinimumSize(QtCore.QSize(600, 0))
        self.frameViewArea.setStyleSheet("border:2px solid rgb(0, 178, 255);")
        self.frameViewArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameViewArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameViewArea.setLineWidth(1)
        self.frameViewArea.setObjectName("frameViewArea")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameViewArea)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayoutViews.addWidget(self.frameViewArea, 0, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listViewOption = QtWidgets.QListView(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewOption.sizePolicy().hasHeightForWidth())
        self.listViewOption.setSizePolicy(sizePolicy)
        self.listViewOption.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.listViewOption.setFont(font)
        self.listViewOption.setStyleSheet("border-top: 2px solid rgb(45, 255, 0);\n"
"border-right: 2px solid rgb(45, 205, 0);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"selection-color: rgba(0, 255, 193, 150);\n"
"")
        self.listViewOption.setLineWidth(2)
        self.listViewOption.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listViewOption.setMovement(QtWidgets.QListView.Static)
        self.listViewOption.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listViewOption.setViewMode(QtWidgets.QListView.ListMode)
        self.listViewOption.setModelColumn(0)
        self.listViewOption.setUniformItemSizes(False)
        self.listViewOption.setBatchSize(200)
        self.listViewOption.setSelectionRectVisible(True)
        self.listViewOption.setItemAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.listViewOption.setObjectName("listViewOption")
        self.verticalLayout.addWidget(self.listViewOption)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setStyleSheet("border: 2px solid rgb(45, 175, 0);")
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frameViewState = QtWidgets.QFrame(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameViewState.sizePolicy().hasHeightForWidth())
        self.frameViewState.setSizePolicy(sizePolicy)
        self.frameViewState.setStyleSheet("border-right: 2px solid rgb(45, 155, 0);\n"
"border-bottom: 2px solid rgb(45, 105, 0);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.frameViewState.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameViewState.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameViewState.setLineWidth(0)
        self.frameViewState.setObjectName("frameViewState")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameViewState)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbViewState = QtWidgets.QLabel(self.frameViewState)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbViewState.sizePolicy().hasHeightForWidth())
        self.lbViewState.setSizePolicy(sizePolicy)
        self.lbViewState.setStyleSheet("border-right: 0px solid rgb(45, 155, 0);\n"
"border-bottom: 0px solid rgb(45, 105, 0);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lbViewState.setText("")
        self.lbViewState.setObjectName("lbViewState")
        self.gridLayout_3.addWidget(self.lbViewState, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frameViewState)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(MachineVisionWin)
        QtCore.QMetaObject.connectSlotsByName(MachineVisionWin)

    def retranslateUi(self, MachineVisionWin):
        _translate = QtCore.QCoreApplication.translate
        MachineVisionWin.setWindowTitle(_translate("MachineVisionWin", "Form"))
