# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CameraWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CameraWin(object):
    def setupUi(self, test):
        test.setObjectName("test")
        test.resize(800, 600)
        self.groupBox = QtWidgets.QGroupBox(test)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 741, 471))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 721, 431))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.camerLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.camerLayout.setContentsMargins(0, 0, 0, 0)
        self.camerLayout.setObjectName("camerLayout")
        self.switchCamera = QtWidgets.QPushButton(test)
        self.switchCamera.setGeometry(QtCore.QRect(120, 530, 113, 32))
        self.switchCamera.setObjectName("switchCamera")
        self.takePic = QtWidgets.QPushButton(test)
        self.takePic.setGeometry(QtCore.QRect(520, 530, 113, 32))
        self.takePic.setObjectName("takePic")

        self.retranslateUi(test)
        QtCore.QMetaObject.connectSlotsByName(test)

    def retranslateUi(self, test):
        _translate = QtCore.QCoreApplication.translate
        test.setWindowTitle(_translate("test", "test"))
        self.groupBox.setTitle(_translate("test", "摄像头"))
        self.switchCamera.setText(_translate("test", "打开摄像头"))
        self.takePic.setText(_translate("test", "拍照"))
